apiVersion: extensions/v1beta1
metadata:
    name: ${project.artifactId}
spec:
    replicas: 1
    template:
        metadata:
          labels:
        spec:
          securityContext:
            runAsUser: 1000
            fsGroup: 2000
          imagePullSecrets:
            - name: ${order.management.deployment.registry}-secret
          containers:
            - name: ${project.artifactId}-container
              restartPolicy: Never
              imagePullPolicy: Always
              volumeMounts:
                - name: ${project.artifactId}-config-volume
                  mountPath: /deployments/config
              resources:
                  requests:
                    memory: ${order.management.deployment.pod.resource.requestmemory}
                  limits:
                    memory: ${order.management.deployment.pod.resource.limitmemory}
              env:
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${project.artifactId}-secrets
                      key: spring.datasource.username.${order.management.deployment.stage}
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${project.artifactId}-secrets
                      key: spring.datasource.password.${order.management.deployment.stage}
          volumes:
            - name: ${project.artifactId}-config-volume
              configMap:
                name: ${project.artifactId}-config